wallet_intel:
  description: >
    Analyze the following instruction and take appropriate action using tools: {user_input}
    Handle balance checks, valuation, and conditional transfers.

  expected_output: >
    Respond with SOL balance, current valuation, or transfer confirmation.
